telegram_export_dir = ""

[telegram_bot]
token = ""
chat_id = ""

[server]
address = "" # IP or domain.name
web_port = 443
verify_ssl = false # or true if needed
access_token = ""

[chat]
type = "group" # available: personal, group, channel, supergroup
name = "" # only for group, channel, supergroup
supergroup_topic_name_template = "{topic} | {supergroup}" # only for supergroup. Available: topic – topic's name, supergroup's name from name param
owner = "" # who created chat(s)

[chat.datetime]
view_original_time_in_message = false # or true if needed
timezone = "GMT" # need if view_original_time_in_message = true
caption = "" # example: f"{caption}{dt}"

[chat.voice_message]
convert_voice_message_to_video = true
cover_image = "cover/ru.png" # by default "cover/en.png"

[chat.stickers]
convert_telegram_stickers_to_webp = true

[registration]
auto = true # or true if needed
email_domain = "" # If it does not exist, the external server name will be substituted.
default_password = ""