[project]
name = "telegram-trueconf-migration"
version = "1.0.1"
description = "Secure сhat transfer from Telegram to TrueConf"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.26.0",
    "cairosvg>=2.9.0",
    "colorama>=0.4.6",
    "ffmpeg-python>=0.2.0",
    "lottie>=0.7.2",
    "orjson>=3.11.7",
    "pillow<12.0.0",
    "progress>=1.6.1",
    "python-trueconf-bot>=1.1.7",
    "tomlkit>=0.14.0",
    "tqdm>=4.67.3",
    "transliterate>=1.10.2",
]
